# https://docs.percona.com/percona-xtradb-cluster/8.0/load-balance-proxysql.html#manual-configuration
---
- name: Configure ProxySQL
  hosts: ProxySQL
  gather_facts: yes
  become: yes

  vars:
    required_packages:
      - percona-xtradb-cluster-client
      - proxysql2

  vars_files:
    - ../../../vault.yml

  tasks:
    - name: Download the repository package
      ansible.builtin.get_url:
        url: "https://repo.percona.com/apt/percona-release_latest.generic_all.deb"
        dest: "/tmp/percona-release_latest.generic_all.deb"

    - name: Install the package with dpkg
      ansible.builtin.apt:
        deb: "/tmp/percona-release_latest.generic_all.deb"

    - name: Update apt repository cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Enable the release repository for Percona XtraDB Cluster
      ansible.builtin.shell: percona-release setup pxc80

    - name: Install Required Packages
      package:
        name: "{{ required_packages }}"
        state: present