# https://docs.percona.com/percona-xtradb-cluster/8.0/apt.html#install-from-repository
# NOTE: You will need to install the hashi_vault plugin for ansible to use the lookup plugin.
# ansible-galaxy collection install community.hashi_vault
---
- name: Configure Percona XtraDB Cluster (Wrapper)
  hosts: PerconaCluster
  gather_facts: yes
  become: yes

  vars:
    vault_addr: "{{ hashicorp.vault.address }}"
    vault_token: "{{ hashicorp_vault_token }}"
    vault_secret_path: "kv/data/percona_cluster/certificates"
    prerequisite_packages:
      - wget
      - gnupg2
      - lsb-release
      - curl
      - python3-pexpect
      - python3-mysqldb

  vars_files:
    - ../../../vault.yml

  tasks:
#    - name: Update apt repository cache
#      ansible.builtin.apt:
#        update_cache: yes
#
#    - name: Install Required Packages
#      package:
#        name: "{{ prerequisite_packages }}"
#        state: present
#
#    - name: Configure Percona XtraDB Cluster
#      include_tasks: "configure_percona_xtradb_cluster.yml"
#
#    - name: Retrieve certificates from bootstrap node.
#      include_tasks: "store_certificates.yml"
#      when: bootstrap is defined and bootstrap == "yes"

    - name: Deploy certificates to other nodes.
      include_tasks: "deploy_certificates.yml"
      when: bootstrap is not defined or bootstrap == "no"