# https://docs.percona.com/percona-xtradb-cluster/8.0/load-balance-proxysql.html#manual-configuration
---
- name: Configure ProxySQL
  hosts: ProxySQL
  gather_facts: yes
  become: yes

  vars:
    required_packages:
      - percona-xtradb-cluster-client
      - proxysql2
      - python3-mysqldb

  vars_files:
    - ../../../vault.yml

  tasks:
#    - name: Download the repository package
#      ansible.builtin.get_url:
#        url: "https://repo.percona.com/apt/percona-release_latest.generic_all.deb"
#        dest: "/tmp/percona-release_latest.generic_all.deb"
#
#    - name: Install the package with dpkg
#      ansible.builtin.apt:
#        deb: "/tmp/percona-release_latest.generic_all.deb"
#
#    - name: Update apt repository cache
#      ansible.builtin.apt:
#        update_cache: yes
#
#    - name: Enable the release repository for Percona XtraDB Cluster
#      ansible.builtin.shell: percona-release setup pxc80
#
#    - name: Install Required Packages
#      package:
#        name: "{{ required_packages }}"
#        state: present

    - name: Retrieve proxySQL admin password from HashiCorp Vault
      set_fact:
        proxysql_creds: "{{ lookup('hashi_vault', 'secret=kv/data/percona_cluster/proxy_sql token={{ hashicorp_vault_token }} url={{ hashicorp.vault.address }}') }}"
      no_log: true

#    - name: Change default proxysql admin password
#      mysql_user:
#        login_user: admin
#        login_password: admin
#        login_port: 6032
#        host: 127.0.0.1
#        user: admin
#        password: "{{ proxysql_creds.admin_password }}"

    - name: Change default proxysql admin password
      ansible.builtin.command:
        cmd: mysql -u admin -e "UPDATE global_variables SET variable_value='admin:{{ proxysql_creds.admin_password }}' WHERE variable_name='admin-admin_credentials'; LOAD ADMIN VARIABLES TO RUNTIME; SAVE ADMIN VARIABLES TO DISK;"
      environment:
        MYSQL_PWD: admin
        MYSQL_HOST: 127.0.0.1
        MYSQL_TCP_PORT: 6032

    - debug:
        msg: |
          Waiting for the user to bootstrap the cluster and start at least 1 other node to the cluster before setting up ProxySQL.
          To bootstrap the cluster, run the following command on the bootstrap node:
            "sudo service mysql bootstrap-pxc" or "sudo systemctl start mysql@bootstrap.service"
          To start the other nodes, run the following command on the other nodes:
            "sudo service mysql start" or "sudo systemctl start mysql"
          

    - name: Retrieve MySQL Root user password from HashiCorp Vault
      # NOTE: This password is created manually and stored in vault at path below. 36 characters generated by random.org
      set_fact:
        percona_creds: "{{ lookup('hashi_vault', 'secret=kv/data/percona_cluster/pxc-cluster token={{ hashicorp_vault_token }} url={{ hashicorp.vault.address }}') }}"
      no_log: true

    - name: Wait for Percona XtraDB Cluster to be ready
      block:
        - name: Query cluster size
          mysql_query:
            login_host: "{{ groups['PerconaCluster'][0] }}" # This should be the bootstrap node
            login_user: root
            login_password: "{{ percona_creds.root_password }}"
            query: "SHOW STATUS LIKE 'wsrep_cluster_size';"
          register: cluster_status
          until: cluster_status.query_result[0][0].Value | int > 1
          retries: 120 # 120 retries * 5 seconds = 10 minutes to timeout
          delay: 5
          ignore_errors: yes # The DB may not be ready to query yet.
          failed_when: cluster_status.retries == 120 # So fail on the timeout.
