# https://docs.percona.com/percona-xtradb-cluster/8.0/apt.html#install-from-repository
---
- name: Install Percona XtraDB Cluster
  hosts: PerconaCluster
  gather_facts: yes
  become: yes

  vars:
    prerequisite_packages:
      - wget
      - gnupg2
      - lsb-release
      - curl
      - python3-pexpect

  tasks:
    - name: Update apt repository cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install prerequisite packages
      package:
        name: "{{ prerequisite_packages }}"
        state: present

    - name: Download the repository package
      ansible.builtin.get_url:
        url: "https://repo.percona.com/apt/percona-release_latest.generic_all.deb"
        dest: "/tmp/percona-release_latest.generic_all.deb"

    - name: Install the package with dpkg
      ansible.builtin.apt:
        deb: "/tmp/percona-release_latest.generic_all.deb"

    - name: Refresh the local cache to update the package information
      ansible.builtin.apt:
        update_cache: yes

    - name: Enable the release repository for Percona XtraDB Cluster
      ansible.builtin.shell: percona-release setup pxc80

    - name: Install the Percona XtraDB Cluster package
      expect:
        command: apt-get -y install percona-xtradb-cluster
        responses:
          'Enter root password:': 'password'
          'Re-enter root password:': 'password'
          'Select default authentication plugin': '1'
      become: yes
      environment:
        DEBIAN_FRONTEND: readline