---
# NOTE: You will need the hashi_vault plugin for ansible to use the lookup plugin.
# ansible-galaxy collection install community.hashi_vault

    - name: Define permissions levels for each certificate
      set_fact:
        file_permissions:
          ca-key.pem: '0600'
          ca.pem: '0644'
          client-cert.pem: '0644'
          client-key.pem: '0600'
          private_key.pem: '0600'
          public_key.pem: '0644'
          server-cert.pem: '0644'
          server-key.pem: '0600'

    - name: Retrieve certifcates from hashicorp vault
      community.hashi_vault.vault_read:
        url: "{{ vault_addr }}"
        token: "{{ vault_token }}"
        path: "{{ vault_secret_path }}"
      register: percona_certificates

    - debug:
        msg: "{{ percona_certificates.data.data.data.ca }}"

    - debug:
        msg: "{{ percona_certificates.data.data.data }}"

    - name: Get list of keys from percona_certificates
      debug:
        msg: "{{ item.key }}"
      loop: "{{ percona_certificates.data.data.data | dict2items }}"

    - name: Deploy certificates to other nodes
      ansible.builtin.copy:
        content: "{{ item.value }}"
        dest: "/var/lib/mysql/{{ item.key }}"
        owner: mysql
        group: mysql
        mode: "{{ file_permissions[item.key] }}"
      loop: "{{ percona_certificates.data.data.data | dict2items }}"