---
# NOTE: You will need the hashi_vault plugin for ansible to use the lookup plugin.
# ansible-galaxy collection install community.hashi_vault

    - name: Retrieve certifcates from hashicorp vault
      community.hashi_vault.vault_read:
        url: "{{ vault_addr }}"
        token: "{{ vault_token }}"
        path: "{{ vault_secret_path }}"
      register: percona_certificates

    - debug:
        msg: "{{ percona_certificates.data.data.data.ca }}"

    - debug:
        msg: "{{ percona_certificates.data.data.data }}"

    - name: Get list of keys from percona_certificates
      debug:
        msg: "{{ item.key }}"
      loop: "{{ percona_certificates.data.data.data | dict2items }}"