---
# NOTE: You will need the hashi_vault plugin for ansible to use the lookup plugin.
# ansible-galaxy collection install community.hashi_vault

#    - name: Retrieve the ca-key certficate
#      ansible.builtin.slurp:
#        src: /var/lib/mysql/ca-key.pem
#      register: ca_key_pem
#
#    - name: Retrieve the ca certficate
#      ansible.builtin.slurp:
#        src: /var/lib/mysql/ca.pem
#      register: ca_pem
#
#    - name: Store ca-key.pem in Vault
#      community.hashi_vault.vault_write:
#        url: "{{ vault_addr }}"
#        token: "{{ vault_token }}"
#        path: "{{ vault_secret_path }}"
#        data:
#          data:
#            ca-key: "{{ ca_key_pem.content | b64decode }}"
#            ca:     "{{ ca_pem.content | b64decode}}"

    - name: Define list of certificate files
      set_fact:
        cert_files:
          - ca-key.pem
          - ca.pem
          - client-cert.pem
          - client-key.pem
          - private_key.pem
          - public_key.pem
          - server-cert.pem
          - server-key.pem

    - name: Retrieve and store certificates in Vault
      block:
        - name: Retrieve the {{ item }} certificate
          ansible.builtin.slurp:
            src: "/var/lib/mysql/{{ item }}"
          register: slurped_cert

        - name: Store {{ item }} in Vault
          community.hashi_vault.vault_write:
            url: "{{ vault_addr }}"
            token: "{{ vault_token }}"
            path: "{{ vault_secret_path }}"
            data:
              data:
                "{{ item }}": "{{ slurped_cert.content | b64decode }}"
      loop: "{{ cert_files }}"