---
# NOTE: You will need the hashi_vault plugin for ansible to use the lookup plugin.
# ansible-galaxy collection install community.hashi_vault

    - name: Retrieve the ca-key.pem certificate
      ansible.builtin.slurp:
        src: /var/lib/mysql/ca-key.pem
      register: ca_key_pem

    - name: Retrieve the ca.pem certificate
      ansible.builtin.slurp:
        src: /var/lib/mysql/ca.pem
      register: ca_pem

    - name: Retrieve the client-cert.pem certificate
      ansible.builtin.slurp:
        src: /var/lib/mysql/client-cert.pem
      register: client_cert_pem

    - name: Retrieve the client-key.pem certificate
      ansible.builtin.slurp:
        src: /var/lib/mysql/client-key.pem
      register: client_key_pem

    - name: Retrieve the private_key.pem certificate
      ansible.builtin.slurp:
        src: /var/lib/mysql/private_key.pem
      register: private_key_pem

    - name: Retrieve the public_key.pem certificate
      ansible.builtin.slurp:
        src: /var/lib/mysql/public_key.pem
      register: public_key_pem

    - name: Retrieve the server-cert.pem certificate
      ansible.builtin.slurp:
        src: /var/lib/mysql/server-cert.pem
      register: server_cert_pem

    - name: Retrieve the server-key.pem certificate
      ansible.builtin.slurp:
        src: /var/lib/mysql/server-key.pem
      register: server_key_pem

    - name: Store certificates in Vault
      community.hashi_vault.vault_write:
        url: "{{ vault_addr }}"
        token: "{{ vault_token }}"
        path: "{{ vault_secret_path }}"
        data:
          data:
            ca-key: "{{ ca_key_pem.content | b64decode }}"
            ca: "{{ ca_pem.content | b64decode }}"
            client-cert: "{{ client_cert_pem.content | b64decode }}"
            client-key: "{{ client_key_pem.content | b64decode }}"
            private_key: "{{ private_key_pem.content | b64decode }}"
            public_key: "{{ public_key_pem.content | b64decode }}"
            server-cert: "{{ server_cert_pem.content | b64decode }}"
            server-key: "{{ server_key_pem.content | b64decode }}"