---
- name: Generate Let's Encrypt Wildcard Certificates
  hosts: jenkins.internal.levantine.io
  gather_facts: yes
  become: yes

  vars:
    certbot_email: letsencrypt@levantine.io
    certbot_install_dir: /etc/letsencrypt

  tasks:
    - name: Install required packages
      become: true
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - certbot

    - name: Create directories for Let's Encrypt certificates
      file:
        path: "/etc/letsencrypt/{{ item }}"
        state: directory
        mode: 0700
      with_items: "{{ domains }}"

    - name: Generate Let's Encrypt Wildcard Certificates
      command: certbot certonly --non-interactive --agree-tos --email "{{ certbot_email }}" --manual --preferred-challenges=dns --manual-public-ip-logging-ok --domain "*.{{ item }}"
      loop: "{{ domains }}"
      register: cert_generation

    - name: Print DNS records for manual update (Will automate later)
      debug:
        msg: |
          To complete the DNS challenge, you need to add the following DNS records for _acme-challenge.{{ item.item }}:
          - Type: TXT
          - Name: _acme-challenge.{{ item.item }}
          - Value: "{{ item.item_validation.stdout }}"
      loop: "{{ cert_generation.results }}"
