---
- name: Generate Let's Encrypt Wildcard Certificates
  hosts: jenkins.internal.levantine.io
  gather_facts: yes
  become: yes

  vars:
    certbot_email: letsencrypt@levantine.io
    certbot_install_dir: /etc/letsencrypt

  tasks:
    - name: Install required packages
      become: true
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - certbot

    - name: Create directories for Let's Encrypt certificates
      file:
        path: "/etc/letsencrypt/{{ item }}"
        state: directory
        mode: 0700
      with_items: "{{ domains }}"

    - name: Generate Let's Encrypt Wildcard Certificates
      # For 2 domains, root domain and all subdomains of the root domain
      command: certbot certonly --non-interactive --agree-tos --email "{{ certbot_email }}" --manual --preferred-challenges=dns --domain "*.{{ item }}" --domain "{{ item }}"
      loop: "{{ domains }}"
      register: cert_generation

# NOTE: For further automation, this will need access to R53 to read/create/modify DNS records
# For now, just take the generate command and run it manually since it will prompt for DNS changes and that's not something we can do automatically at this time