---
- name: Pull and run nginx-proxy container
  hosts: VMWareDockerHosts
  gather_facts: yes
  become: yes

  tasks:

    # The docker module documentation mainly focuses on getting information on a specific container
    # and it was difficult to find a way to just get a list of running containers. In any case, since this
    # just listing, it should still be declarative
    - name: Get running container names
      ansible.builtin.command: 'docker ps --format "{{\.Names}} --filter status=running"'
      register: running_containers_raw
      changed_when: false

    - name: Pull nginx-proxy image
      docker_image:
        name: jwilder/nginx-proxy
        tag: latest
      register: image_pull

    - name: Run nginx-proxy container
      docker_container:
        name: nginx-proxy
        image: jwilder/nginx-proxy:latest
        ports:
          - "80:80"
        volumes:
          - "/var/run/docker.sock:/tmp/docker.sock:ro"
        detach: yes
      when: image_pull.changed
      register: container_start

    - name: Restart nginx-proxy container if image was pulled
      docker_container:
        name: nginx-proxy
        state: restarted
      when: image_pulled.changed and not container_start.changed
      register: container_restart

    - name: Restart running containers if nginx-proxy container was restarted
      docker_container:
        name: "{{ item }}"
        state: restarted
      loop: "{{ running_containers_raw.stdout_lines }}"
      when: container_restart.changed and item != 'nginx-proxy'
