---
- name: Manage Docker Containers
  hosts: localhost

  vars:
    container_names: "{{ container_names_string.split(',') }}"

  tasks:
    - debug:
        msg: "Deploying Theia Services"

    - name: Get CWD
      debug:
        msg: "{{ lookup('env', 'PWD') }}"

    - debug:
        msg: '{{ supported_containers }}'

    - name: Validate Supported Containers
      debug:
        msg: 'Validating {{ item_name }}'
      loop: "{{ container_names }}"
      loop_control: # Think of this like a for loop "For item in container_names"
        loop_var: item_name
      failed_when: item_name not in supported_containers
      register: unsupported_containers