---
- name: Debug Test
  hosts: localhost

  vars:
    foo: "bar"

  tasks:
    - name: rp_flow
      debug:
        msg: "{{ rp_flow }}"
      loop: "{{ domains }}"

    - name: pplocation
      debug:
        msg: "{{ reverse_proxy_configs[rp_flow].proxy_pass_location }}"
      loop: "{{ domains }}"
