---
- name: Debug Test
  hosts: localhost
  vars_files:
    - ../../vault.yml
  vars:
    foo: "bar"

  tasks:

    - name: Show Foo
      debug:
        msg: "{{ inventory_hostname.split('.')[0] }}"

    - name: Show Key
      debug:
        msg: "{{ wireguard[env_context]['secret_key'] }}"

#  VIRTUAL_HOST: "{{ supported_containers[container_name]['env_vars']['VIRTUAL_HOST'] }}"

    - name: Show Key
      debug:
        msg: "{{ wireguard[env_context]['secret_key'][inventory_hostname.split('.')[0]] }}"
