---
- name: Debug Test
  hosts: localhost
  vars:
    foo: "bar"
    ssl_certs: # These will be filled in by the HashiCorp Vault lookup in this playbook
      cert: "{{ ssl_certs.cert }}"
      chain: "{{ ssl_certs.chain }}"
      fullchain: "{{ ssl_certs.fullchain }}"
      privkey: "{{ ssl_certs.privkey }}"

  tasks:

#    - name: Show Foo
#      debug:
#        msg: "Hello World"

    - name: Retrieving SSL Certs for levantine.io
      set_fact:
        ssl_certs:
          cert: "certy"
          chain: "chainy"
          fullchain: "fullchainy"
          privkey: "privkeyyy"

    - name: Show SSL Cert Keys
      debug:
        msg: "{{ item }}"
      with_items:
        "{{ ssl_certs }}"

    - name: Show SSL Cert values
      debug:
        msg: "{{ ssl_certs[item] }}"
      with_items:
        "{{ ssl_certs }}"