---
- name: Manage Docker Containers
  hosts: VMWareDockerHosts
  become: true

  vars:
    container_names: "{{ container_names_string.split(',') }}"
    container_action: "{{ container_action_string }}"
    supported_containers: "{{ supported_containers }}"

  tasks:
    - name: Validate container names
      debug:
        msg: "Container '{{ item }}' is not a supported container. Skipping."
      loop: "{{ container_names }}"
      loop_control: # Think of this like a for loop "For item in container_names"
        loop_var: item_name
      when: item_name not in supported_containers | map(attribute='name') | list
      register: unsupported_containers
      changed_when: false

    - name: Start Docker containers
      docker_container:
        name: "{{ item }}"
        state: started
        env:
          - "{{ supported_containers | selectattr('name', 'in', container_names) | map(attribute='env_vars') | list | flatten }}"
      loop: "{{ container_names }}"
      when:
        - container_action == 'start'
        - item not in unsupported_containers.results | map(attribute='item_name') | list

    - name: Stop Docker containers
      docker_container:
        name: "{{ item }}"
        state: stopped
      loop: "{{ container_names }}"
      when:
        - container_action == 'stop'
        - item not in unsupported_containers.results | map(attribute='item_name') | list
