---
- name: Deploy Nginx Reverse Proxy Configuration Files
  hosts: Nginx
  become: yes

  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Configure Nginx Reverse Proxies
      template:
        src: "templates/reverse_proxy.j2"
        dest: "/etc/nginx/conf.d/{{ item }}.conf"
        owner: root
        group: root
        mode: '0644'
      loop: "{{ domains }}"

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
