---
- name: Deploy Nginx Reverse Proxy Configuration Files
  hosts: Nginx
  become: yes

  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Configure Nginx Reverse Proxies
      template:
        src: "templates/reverse_proxy.j2"
        dest: "/etc/nginx/conf.d/{{ item }}.conf"
        owner: root
        group: root
        mode: '0644'
      loop: "{{ domains }}"

    - name: Configure Theia One Off Reverse Proxy DownStream
      copy:
        src: "downstream/files/theia_reverse_proxy_downstream.conf"
        dest: "/etc/nginx/conf.d/theia_reverse_proxy.conf"
        remote_src: no
      when: rp_flow is defined && rp_flow == "downstream"

    - name: Configure Theia One Off Reverse Proxy UpStream
      copy:
        src: "upstream/files/theia_reverse_proxy_upstream.conf"
        dest: "/etc/nginx/conf.d/theia_reverse_proxy.conf"
        remote_src: no
      when: rp_flow is defined && rp_flow == "upstream"

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
