---
  - name: debug 1
    debug:
      msg: "{{ wireguard[env_context]['secret_key']['client']['jenkins'] }}"

  - name: debug 2
    debug:
      msg: "{{ wireguard[env_context]['secret_key']['client']['vmwarebastion'] }}"

  - name: debug 3
    debug:
      msg: "{{ wireguard[env_context]['secret_key']['client'][inventory_hostname.split('.')[0]] }}"

  - name: Configure Wireguard Clients
    template:
      src: "templates/client_wg0.conf.j2"
      dest: "/etc/wireguard/wg0.conf"
      owner: root
      group: root
      mode: '0644'