---

  - name: Configure Wireguard Clients
    template:
      src: "templates/client_wg0.conf.j2"
      dest: "/etc/wireguard/wg0.conf"
      owner: root
      group: root
      mode: '0644'
    register: wireguard_client_config

  - name: Enable and start the Wireguard Client service daemon
    systemd:
      name: wg-quick@wg0
      state: started
      enabled: yes
    register: wireguard_client_service

  - name: Check if Wireguard Client is Running
    ansible.builtin.command: "wg show | grep wg0"
    register: wireguard_client_status
    ignore_errors: yes

  - name: Restart Wireguard Server
    systemd:
      name: wg-quick@wg0
      state: restarted
    when:
      - (wireguard_client_config.changed and wireguard_client_service.not_changed) or
      - (wireguard_client_status.failed)