---

  - name: Configure Wireguard Clients
    template:
      src: "templates/client_wg0.conf.j2"
      dest: "/etc/wireguard/wg0.conf"
      owner: root
      group: root
      mode: '0644'
    register: wireguard_client_config

  - name: Enable and start the Wireguard Client service daemon
    systemd:
      name: wg-quick@wg0
      state: started
      enabled: yes
    register: wireguard_client_service

  - name: Check if Wireguard Client is Running
    ansible.builtin.shell: "wg show | grep wg0"
    register: wireguard_client_status
    ignore_errors: yes

  - name: Restart Wireguard Server
    systemd:
      name: wg-quick@wg0
      state: restarted
    when: (wireguard_client_config.changed and not wireguard_client_service.changed) or
          (wireguard_client_status.failed)

  - name: Configure wireguard watcher script
    template:
      src: "templates/wireguard_watcher.sh.j2"
      dest: "/etc/wireguard/wireguard-watcher.sh"
      owner: root
      group: root
      mode: '0644'
    register: wg_watcher_script

  - name: Configure wireguard watcher service daemon
    copy:
      src: "templates/wireguard-watcher.service"
      dest: "/lib/systemd/system/wireguard-watcher.service"
      owner: root
      group: root
      mode: '0644'
    register: wireguard_watcher_service

  - name: Reload systemd daemon
    systemd:
      daemon_reload: yes
    when: wireguard_watcher_service.changed

  - name: Start the Wireguard Watcher service
    systemd:
      name: wireguard-watcher
      state: started
      enabled: yes

  - name: Restart the Wireguard Watcher service
    systemd:
      name: wireguard-watcher
      state: restarted
    when: wireguard_watcher_service.changed or wg_watcher_script.changed