---
  - name: Initialize the Kubernetes control plane
    ansible.builtin.command: kubeadm init --cri-socket "{{ DataGatewayK8Cluster.cri_socket }}" --control-plane-endpoint "{{ DataGatewayK8Cluster.control_plane_endpoint }}"
    register: kubeadm_init
    when: node is defined and node == "controller"

  - name: Add KUBECONFIG export to bash profile
    ansible.builtin.lineinfile:
      path: ~/.bash_profile
      line: 'export KUBECONFIG=/etc/kubernetes/admin.conf'
      create: yes
      insertafter: EOF

  - name: Copy flannel.yaml from local to remote
    ansible.builtin.copy:
        src: templates/kube-flannel.yml
        dest: "/etc/kubernetes/kube-flannel.yml"
        owner: "{{ ansible_env.USER }}"
        group: "{{ ansible_env.USER }}"
        mode: '0644'
        remote_src: no

# NOTE: 2024-07-08: Downloading the kube-flannel.yml file has been very unreliable, so just checked it into the repo.
  # https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  - name: Apply Flannel network
    ansible.builtin.command: kubectl apply -f /etc/kubernetes/kube-flannel.yml
    when: node is defined and node == "controller"

  - name: Store secrets in Hashicorp Vault
    include_tasks: store_control_plane_secrets.yml
    when: node is defined and node == "controller"
