---
  - name: Initialize the Kubernetes control plane
    ansible.builtin.command: kubeadm init --cri-socket "{{ DataGatewayK8Cluster.cri_socket }}" --control-plane-endpoint "{{ DataGatewayK8Cluster.control_plane_endpoint }}"
    register: kubeadm_init
    when: node is defined and node == "controller"

  - name: Store secrets in Hashicorp Vault
    include_tasks: store_control_plane_secrets.yml
    when: node is defined and node == "controller"

  - name: debug
    ansible.builtin.debug:
      msg: "{{ kubeadm_join_cmd }}"
    when: node is defined and node == "controller"

  - name: Apply Flannel network
    ansible.builtin.command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
    when: node is defined and node == "controller"
