---
#  The join command hostvar is captured in the control plane configuration task: Capture kubeadm join command
# all.yml -> kubernetes_clusters_baseline/setup_kubernetes_wrapper.yml -> configure_control_plane.yml

  - name: Retrieve token and hash from Vault
    community.hashi_vault.vault_read:
        url: "{{ vault_addr }}"
        token: "{{ vault_token }}"
        path: "{{ vault_token_path }}"
    register: k8s_tokens
    no_log: true

  - name: Retrieve local registry self signed certs from vault
    community.hashi_vault.vault_read:
        url: "{{ vault_addr }}"
        token: "{{ vault_token }}"
        path: "{{ vault_local_reg_cert_path }}"
    register: local_reg_certs
    no_log: true

  - name: Debug
    debug:
        var: local_reg_certs

# https://distribution.github.io/distribution/about/insecure/#use-self-signed-certificates
# See "Setup local registry to store Docker images to deploy to worker nodes." in configure_control_plane.yml for context
  - name: Deploy local registry certificates
    ansible.builtin.copy:
        content: "{{ local_reg_certs['data']['data']['domain.crt'] }}"
        dest: "/etc/docker/certs.d/{{ DataGatewayK8Cluster.control_plane_endpoint }}:5000/ca.crt"
        owner: root
        group: root
        mode: '0644'

  - name: Join node to the cluster
    ansible.builtin.command: >
        kubeadm join {{ DataGatewayK8Cluster.control_plane_endpoint }}:6443
        --cri-socket {{ DataGatewayK8Cluster.cri_socket }}
        --token {{ k8s_tokens['data']['data']['data']['token'] }}
        --discovery-token-ca-cert-hash {{ k8s_tokens['data']['data']['data']['kubeadm_init_join_ca_cert_hash'] }}
