# https://kubernetes.io/docs/setup/production-environment/#what-s-next
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
# https://github.com/kairen/kubeadm-ansible/tree/master/roles/commons/pre-install/tasks

---
- name: Configure Kubernetes Cluster Baseline
  hosts: DataGatewayK8Cluster
  become: yes
  gather_facts: yes

  vars:
    required_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    kube_packages:
      - kubeadm
      - kubelet
      - kubectl

  vars_files:
    - ../../../vault.yml

  tasks:
    # NOTE: Docker will be installed a few steps earlier in the app.yml playbook -- - import_playbook: installDocker.yml

    - name: Setup Kubernetes Cluster Baseline
      include_tasks: "setup_k8_baseline.yml"

    - name: Configure Control Plane Nodes
      include_tasks: "configure_control_plane.yml"
      when: node is defined and node == "controller"

    - name: Configure Worker Nodes
      include_tasks: "configure_worker_nodes.yml"
      when: node is defined and node == "worker"