# https://docs.ansible.com/ansible/latest/collections/kubernetes/core/k8s_module.html

---
  - name: Deploy DataGateway Kubernetes Configurations
    hosts: DataGatewayK8Cluster
    become: yes
    gather_facts: yes

    vars:
      aws_environment: # These will be filled in by the HashiCorp Vault lookup in this playbook
        AWS_ACCESS_KEY_ID: "{{ aws_creds.access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_creds.secret_key }}"

    vars_files:
      - ../../../vault.yml

    tasks:

      - name: Retrieve AWS Credentials from HashiCorp Vault
        # NOTE: The secret path is created in the main terraform repo when the user is created and key stored in vault at path below
        set_fact:
          aws_creds: "{{ lookup('hashi_vault', 'secret={{ DataGatewayK8Cluster.vault_aws_iam_key_path }} token={{ hashicorp_vault_token }} url={{ hashicorp.vault.address }}') }}"

      - name: Create Kubernetes Secret for AWS ECR
        kubernetes.core.k8s:
          state: present
          definition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: aws-ecr-credentials
            type: kubernetes.io/dockerconfigjson
            data:
              .dockerconfigjson: "{{ ( {'auths': { 'https://index.docker.io/v1/': { 'auth': (aws_creds.access_key + ':' + aws_creds.secret_key) | b64encode } }} ) | to_json | b64encode }}"

##### NOTE: The following tasks are just to get the latest image in the ECR >>>>>>>>>>>
      - name: Log in to AWS ECR
        shell: "aws ecr get-login-password --region {{ default_region }} | docker login --username AWS --password-stdin {{ account_id }}.dkr.ecr.{{ default_region }}.amazonaws.com"
        environment: "{{ aws_environment }}"

      - name: Get the latest Docker image from ECR
        shell: "aws ecr describe-images --repository-name {{ DataGatewayK8Cluster.aws_ecr_repo_name }} --query 'sort_by(imageDetails, &imagePushedAt) | [-1].imageTags[0]' --output text --region {{ default_region }}"
        environment: "{{ aws_environment }}"
        register: latest_image

      - name: Latest docker image repo path
        set_fact:
          ecr_path: "{{ account_id }}.dkr.ecr.{{ default_region }}.amazonaws.com/{{ DataGatewayK8Cluster.aws_ecr_repo_name }}:{{ latest_image.stdout }}"
#### Latest image identified <<<<<<<<<<<<<<<<<<<<<

      - name: Retrieve Database Credentials from HashiCorp Vault
        set_fact:
          db_creds: "{{ lookup('hashi_vault', 'secret={{ DataGatewayK8Cluster.spring_datasource_password_vault_path }} token={{ hashicorp_vault_token }} url={{ hashicorp.vault.address }}') }}"

      - name: Create Kubernetes Deployment
        kubernetes.core.k8s:
          state: present
          definition:
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: spring-boot-app
            spec:
              replicas: 4
              selector:
                matchLabels:
                  app: spring-boot-app
              template:
                metadata:
                  labels:
                    app: spring-boot-app
                spec:
                  containers:
                  - name: spring-boot-app
                    image: "{{ ecr_path }}"
                    env:
                    - name: spring.datasource.url
                      value: "{{ DataGatewayK8Cluster.spring_datasource_url }}"
                    - name: spring.datasource.username
                      value: "{{ DataGatewayK8Cluster.spring_datasource_username }}"
                    - name: spring.datasource.password
                      value: "{{ db_creds[DataGatewayK8Cluster.spring_datasource_username] }}"
                  imagePullSecrets:
                  - name: aws-ecr-credentials
