--- # This is a wrapper playbook to run the bootstrap playbooks
- import_playbook: user_groups.yml
- import_playbook: users.yml
- import_playbook: bash_profile/manage_bash_profile.yml
- import_playbook: resize_main_diskPartitionWrapper.yml
- import_playbook: installBasicPackages.yml
- import_playbook: configure_time.yml
# - import_playbook: dnsForwardingAndResolution.yml # NOTE: As of 2023-12-14 this is deprecated by PF Sense
- import_playbook: configureHostFile.yml # NOTE: This will soon be deprecated by PF Sense
- import_playbook: configureHostname.yml
- import_playbook: configureDHCP.yml
- import_playbook: configure_DNS_Resolver.yml
- import_playbook: deploySSLCerts.yml
- import_playbook: nginx_reverse_proxy/deployRPConfigs.yml
- import_playbook: theiaOneOff.yml
- import_playbook: ../applications/jenkins/deployReverseProxy.yml
- import_playbook: installDocker.yml
