--- # This is a wrapper playbook to run the bootstrap playbooks
- import_playbook: users.yml
- import_playbook: installBasicPackages.yml
# - import_playbook: dnsForwardingAndResolution.yml
- import_playbook: configureHostFile.yml