---
- name: Ensure DHCP client service is enabled and started
  hosts: all
  become: true
  tasks:

    - name: Install dhclient package
      apt:
        name: isc-dhcp-client
        state: present
      register: dhcp_client_installed

    - name: Restart networking service
      service:
        name: networking
        state: restarted
      when: dhcp_client_installed.changed

# NOTE: As of 2024-03-19 dhclient isn't set up as a systemd service but the package
# is installed and should work by default, so disabling this for now unless there's a problem.

#    - name: Ensure DHCP client service is enabled and started
#      service:
#        name: dhclient
#        enabled: yes
#        state: started