---
- name: Install and configure XFCE desktop environment on Debian 12
  hosts: service
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install XFCE desktop environment
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - xfce4
        - xfce4-goodies
        - lightdm
        - lightdm-gtk-greeter
        - lightdm-gtk-greeter-settings
      register: xfce_install

    - name: Turn off lightdm on startup
      # I only need to start lightdm when I want to use the GUI
      systemd:
        name: lightdm
        enabled: no

    - name: Reboot to apply changes
      ansible.builtin.reboot:
        reboot_timeout: 300
      when: xfce_install.changed