---
- name: Install HashiCorp Vault
  hosts: Vault
  become: yes

# https://developer.hashicorp.com/vault/tutorials/getting-started/getting-started-install
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - gpg

    - name: Add HashiCorp GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg

    - name: Dearmor GPG key
      ansible.builtin.command: gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Verify Keyring
      ansible.builtin.command: gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint

    - name: Add HashiCorp repository to apt sources
      become: yes
      lineinfile:
        path: /etc/apt/sources.list.d/hashicorp.list
        line: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        state: present

    - name: Install HashiCorp Vault
      apt:
        name: vault
        state: present

    - name: Create Vault configuration directory
      file:
        path: /etc/vault.d
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: Create Vault data directory
      file:
        path: /var/lib/vault
        state: directory
        mode: '0755'
        owner: vault
        group: vault

    - name: Create Vault logs directory
      file:
        path: /var/log/vault
        state: directory
        mode: '0755'
        owner: vault
        group: vault

    - name: Create Vault configuration file
      template:
        src: templates/vault.hcl.j2
        dest: /etc/vault.d/vault.hcl
        owner: root
        group: root
        mode: '0644'

    - name: Start and enable Vault service
      systemd:
        name: vault
        state: started
        enabled: yes