---
- name: Ensure DHCP client service is enabled and started
  hosts: all
  become: true
  tasks:

    - name: Install dhclient package
      apt:
        name: isc-dhcp-client
        state: present
      register: dhcp_client_installed

    - name: Restart networking service
      service:
        name: networking
        state: restarted
      when: dhcp_client_installed.changed

    - name: Ensure DHCP client service is enabled and started
      service:
        name: isc-dhcp-client
        enabled: yes
        state: started