---
- name: Configure NTP and Set Time Zone to UTC
  hosts: all
  become: yes

  tasks:
    - name: Set Timezone to UTC on Red Hat/CentOS
      timezone:
        name: UTC
      when: ansible_distribution != 'Alpine'

    - name: Set Timezone to UTC on Alpine Linux
      command: ln -sf /usr/share/zoneinfo/UTC /etc/localtime
      when: ansible_distribution == 'Alpine'
