---
- name: Manage entries in the /etc/hosts file
  hosts: all
  become: yes
  # Note: In the future, we'll be using DNS forwards instead of /etc/hosts; this is just a temporary solution

  tasks:
    - name: Read the existing /etc/hosts file
      shell: cat /etc/hosts
      register: current_hosts
      changed_when: false
      check_mode: false

    - name: Set the content of the /etc/hosts file
      set_fact:
        hosts_content: "{{ current_hosts.stdout }}"

    - name: Show current /etc/hosts content
      debug:
        var: hosts_content

    - name: Add or update host entries
      blockinfile:
        path: /etc/hosts
        block: "{{ host_entries }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        state: present
      when: "'{} {}'.format(item.ip, item.hostname) not in hosts_content"

  handlers:
    - name: Reload the hosts file
      shell: "cat /etc/hosts > /dev/null"  # Touch the file to trigger the reload
