---
- name: Manage entries in the /etc/hosts file
  hosts: all
  become: yes
  # Note: In the future, we'll be using DNS forwards instead of /etc/hosts; this is just a temporary solution
  # NOTE: 2023-12-14 This will soon be deprecated by PF sense
  # NOTE: 2024-04-25 This has been deprecated by OPNSense for general use. But this is going to stay here
  # so that I don't have to reinvent the wheel if i want to use it in the future for some niche use case.
  tasks:
    - name: Read the existing /etc/hosts file
      shell: cat /etc/hosts
      register: current_hosts
      changed_when: false

    - name: Set the content of the /etc/hosts file
      set_fact:
        hosts_content: "{{ current_hosts.stdout }}"

    - name: Add or update host entries
      blockinfile:
        path: /etc/hosts
        block: "{{ host_entries }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        state: present

  handlers:
    - name: Reload the hosts file
      shell: "cat /etc/hosts > /dev/null"  # Touch the file to trigger the reload
