---
- name: Deploy Nginx Reverse Certs
  hosts: Nginx
  become: yes

  tasks:
    - name: Ensure Cert Directory Exists
      file:
        path: /etc/nginx/certs/
        state: directory

    - name: Copy SSL Certs
      copy:
        src: "/etc/letsencrypt/live/{{ item }}"
        dest: /etc/nginx/certs/
      loop: "{{ domains }}"
