---
- name: Deploy Nginx Reverse Certs
  hosts: Nginx
  become: yes

  tasks:
#    - name: Ensure Cert Directory Exists
#      file:
#        path: "/etc/nginx/certs/{{ item }}/"
#        state: directory
#      loop: "{{ domains }}"

    - name: Copy SSL Certs
      copy:
        src: "/home/jenkins/fucking_ansible"
        dest: "/etc/nginx/certs/levantine.io/fuck.you.ansible"
        remote_src: no
      loop: "{{ domains }}"
      become: yes