---
- name: Deploy Nginx Reverse Certs
  hosts: Nginx
  become: yes

  vars_files:
    - ../../vault.yml
  vars:
    ssl_certs: # These will be filled in by the HashiCorp Vault lookup in this playbook
      cert: "{{ ssl_certs.cert }}"
      chain: "{{ ssl_certs.chain }}"
      fullchain: "{{ ssl_certs.fullchain }}"
      privkey: "{{ ssl_certs.privkey }}"

  tasks:
    - name: Ensure Cert Directory Exists for Each Domain
      file:
        path: "/etc/nginx/certs/"
        state: directory
      loop: "{{ domains }}"

    - name: Retrieving SSL Certs for levantine.io
      set_fact:
        ssl_certs: "{{ lookup('hashi_vault', 'secret=kv/data/ssl_certs/levantine_io token={{ hashicorp_vault_token }} url={{ hashicorp.vault.address }}') }}"

    - name: Configure SSL Certs for levantine.io
      copy:
        content: "{{ ssl_certs[item] }}"
        dest: /etc/nginx/certs/levantine.io/{{ item }}.pem
      with_items:
        "{{ ssl_certs }}"
      register: levantine_certs

    - name: Retrieving SSL Certs for nhitruong.com
      set_fact:
        ssl_certs: "{{ lookup('hashi_vault', 'secret=kv/data/ssl_certs/nhitruong_com token={{ hashicorp_vault_token }} url={{ hashicorp.vault.address }}') }}"

    - name: Configure SSL Certs for nhitruong.com
      copy:
        content: "{{ ssl_certs[item] }}"
        dest: /etc/nginx/certs/nhitruong.com/{{ item }}.pem
      with_items:
        "{{ ssl_certs }}"
      register: nhitruong_certs

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
      when: levantine_certs.changed or nhitruong_certs.changed