---
- name: Deploy Nginx Reverse Certs
  hosts: Nginx
  become: yes

  tasks:
    - name: Ensure Cert Directory Exists
      file:
        path: "/etc/nginx/certs/{{ item }}/"
        state: directory
      loop: "{{ domains }}"

#    - name: Copy SSL Certs
#      copy:
#        src: "/etc/letsencrypt/live/{{ item }}"
#        dest: "/etc/nginx/certs/{{ item }}"
#        remote_src: no
#      loop: "{{ domains }}"

# The above stanza doesn't work because ansible is a total idiot and cannot find a path that's right in front of it, even with sudo permissions
# So we copied the certs to home dir copy from that instead.

    - name: Copy SSL Certs
      copy:
        src: "/home/jenkins/certs/{{ item }}"
        dest: "/etc/nginx/certs/{{ item }}"
        remote_src: no
      loop: "{{ domains }}"