---
- name: Install/update basic packages
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    basic_packages:
      - htop # Better than top
      - net-tools # ifconfig and stuff
      - python3-hvac # HashiCorp Vault client
    service_host_packages:
      - snap # The snap packages for needed to install firefox on service host
      - snapd

  tasks:
    - name: Update package cache
      package:
        name: '*'
        state: latest
        update_cache: yes
      ignore_errors: yes # No big deal if this fails

    - name: Install packages
      package:
        name: "{{ basic_packages }}"
        state: present

    - name: Install service host packages
      package:
        name: "{{ service_host_packages }}"
        state: present
      when: "'service' in group_names"