---
- name: Install/update basic packages
  hosts: all:!Jenkins
  gather_facts: yes
  become: yes

  vars:
    basic_packages:
      - htop
      - net-tools

  tasks:
    - name: Update package cache
      package:
        name: '*'
        state: latest
        update_cache: yes
      ignore_errors: yes # No big deal if this fails

    - name: Install packages
      package:
        name: "{{ basic_packages }}"
        state: present