---
- name: Install/update basic packages
  hosts: all
  gather_facts: yes
  become: yes

  vars:
    basic_packages:
      - htop
      - net-tools
#    service_host_packages:
#      - firefox

  tasks:
    - name: Update package cache
      package:
        name: '*'
        state: latest
        update_cache: yes
      ignore_errors: yes # No big deal if this fails

    - name: Install packages
      package:
        name: "{{ basic_packages }}"
        state: present

#    - name: Install service host packages
#      package:
#        name: "{{ service_host_packages }}"
#        state: present
#      when: "'service' in group_names"