---
# Playbook Courtesy of DigitalOcean
# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-20-04

- name: Install Docker
  hosts: Jenkins:VMWareDockerHosts:service:DataGatewayK8Cluster
  become: true

  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Download cri-dockerd binary
      get_url:
        url: "https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.14/cri-dockerd_0.3.14.3-0.debian-bookworm_amd64.deb"
        dest: "/tmp/cri-dockerd_0.3.14.3-0.debian-bookworm_amd64.deb"

    # Regarding cri-dockerd:
    # Note:  https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
    # Docker Engine does not implement the CRI which is a requirement for a container runtime to work with Kubernetes.
    # For that reason, an additional service cri-dockerd has to be installed.
    # cri-dockerd is a project based on the legacy built-in Docker Engine support that was removed from the kubelet in
    # version 1.24.
    # Runtime/ Domain socket: Docker Engine (using cri-dockerd)	unix:///var/run/cri-dockerd.sock

    - name: Install cri-dockerd
      apt:
        deb: "/tmp/cri-dockerd_0.3.14.3-0.debian-bookworm_amd64.deb"

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install docker python package
      package:
        name: "python3-docker"
        state: present