---
- name: Deploy Theia Configs
  hosts: Theia
  become: yes

  tasks:
    - name: Ensure Cert Directory Exists
      file:
        path: "/etc/apache2/certs/"
        state: directory
      loop: "{{ domains }}"

    - name: Copy SSL Certs
      copy:
        src: "/home/jenkins/certs/{{ item }}"
        dest: "/etc/apache2/certs/"
        remote_src: no
      loop: "{{ domains }}"

    - name: Copy apache configs
      copy:
        src: "../applications/theia/files/000-default.conf"
        dest: "/etc/apache2/sites-available/"
        remote_src: no
      loop: "{{ domains }}"

    - name: restart apache
      service:
        name: apache2
        state: restarted

    - name: Copy nightly restart script
      copy:
        src: "../applications/theia/files/nightly_restart.sh"
        dest: "/home/automation/"
        remote_src: no

    - name: Set up nightly restart cron job
      cron: # This is so that the memory doesn't eventually run out. There's a leak somewhere.
        name: "Nightly Restart Job"
        minute: "0"
        hour: "0"
        job: "/bin/bash /home/automation/nightly_restart.sh"
        state: present
