---
- name: Setup users and configure sudoers
  hosts: all
  become: true
  gather_facts: false
  vars:
    enabled_users:
      - name: automation
        authorized_key: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAlK9SYgHttisI9NMozvE0HNroEK2bBG406szUfIGz1Xq+CGTdW1x197nBh36zqa5gYbhQCM/uGKOaGCPB+6R6gW0CpaHjPvcKW+pKAUaEWkQzeRYaS1yEJjD4Fh+DFqgaYKh+VTCH7RC2c6N+YdKKJkaSan2iaI9Z5nLjAxJloepbJBTDnhPQVasqNUykh6ZbYyYM5p3EEhYPrw5bMZJJkyHV44UexfqBmroSgbA87PtyUw/+9T9aG3yYwtAafUZJlZpWbeHdMRW/SVYmt/wCze5x+IAxqjk+48b8HeltR5Nys33VSQybuKNrcnumDNzthLFMQvF4ABO66yCTQ5NaBQ== automation
        group: sudo_all

    disabled_users:
      - name: admin
      - name: debian

  tasks:
    - name: Create users
      user:
        name: "{{ item.name }}"
        group: "{{ item.group }}"
        state: present
        shell: /bin/bash
      with_items: "{{ enabled_users }}"
      no_log: true
      register: create_user

    - debug:
        msg: "{{ create_user.stdout }}"
      when: create_user.failed

    - name: Ensure authorized key exist for users
      authorized_key:
        user: "{{ item.name }}"
        state: present
        key: "{{ item.authorized_key }}"
      with_items: "{{ enabled_users }}"
      no_log: true
      register: create_authorized_key

    - debug:
        msg: "{{ create_authorized_key.stdout }}"
      when: create_authorized_key.failed

    - name: Remove users
      user:
        name: "{{ item.name }}"
        state: absent
        shell: /bin/bash
      with_items: "{{ disabled_users }}"