- name: Create groups and configure group permissions
  hosts: all
  become: yes

  tasks:
    - name: Create group with default sudo permissions
      group:
        name: sudo_all
        state: present

    - name: Configure sudoers file for sudo_all group
      copy:
        content: "%sudo_all ALL=(ALL) NOPASSWD: ALL"
        dest: /etc/sudoers.d/sudo_all
        owner: root
        group: root
        mode: '0440'
      become: yes

#NOTE: As of 2024/14/04 if the limited group is created without users, somehow ubuntu sudoers freaks out
    # and breaks sudo for all users. So for now we remove anything limited_users until we actually have a limited user to add.
    - name: Create group with restricted permissions
      group:
        name: limited_group
        state: absent

#    - name: Ensure limited_group can only access their own home directory
#      copy:
#        content: "%limited_group ALL=(ALL) NOPASSWD: /bin/ls"
#        dest: /etc/sudoers.d/limited_group
#        owner: root
#        group: root
#        mode: '0440'
#      become: yes

    - name: Ensure limited_group file is deleted
      file:
        path: /etc/sudoers.d/limited_group
        state: absent
      become: yes
