---
- name: Ensure dhclient service is enabled and started (Alpine Linux)
  hosts: VMWareDockerHosts
  become: true
  tasks:
    - name: Ensure dhclient package is installed
      apk:
        name: dhclient
        state: present
        update_cache: yes

    - name: Enable and start dhclient service
      service:
        name: dhclient
        enabled: yes
        state: started
