[VMWareDockerHosts]
192.168.0.31 # Alpine Docker Host 1

[BastionHosts]
10.0.0.1 # AWS EC2 Nginx/WireGuard Instance
192.168.1.10 # VMWare Nginx/WireGuard Instance

[Theia]
192.168.1.30 # Theia VMWare Instance

[Jenkins]
192.168.1.20 # Jenkins VMWare Instance
