[VMWareDockerHosts]
192.168.1.3 # Alpine Docker Host 1

[BastionHosts]
10.0.0.1 # AWS EC2 Nginx/WireGuard Instance
192.168.1.2 # VMWare Nginx/WireGuard Instance

[Theia]
192.168.1.5 # Theia VMWare Instance

[Jenkins]
192.168.1.4 # Jenkins VMWare Instance
