---
- name: Start Theia Services
  hosts: Theia

  tasks:
    - name: Start Theia Front End Service
      shell: pm2 start /opt/theia/frontend/py/app.py --interpreter python3

    - name: Start Theia Back End Service
      shell: pm2 start /opt/theia/rabbitMQ/rbt.py --interpreter python3

    - name: Start Theia Tailon Log Service
      shell: pm2 start "tailon -b localhost:1337 -f /opt/theia/logs/* /var/log/apache2/*.log /var/log/syslog /var/log/auth.log /var/log/dmesg /var/log/rabbitmq/log/crash.log /var/log/rabbitmq/*.log" -n tailon