---
- name: Configure Splunk Server
  hosts: Splunk
  gather_facts: true
  become: true

  vars_files:
    - ../../../vault.yml
  vars:
    account_id: "{{ aws.account_id }}"
    default_region: "{{ aws.default_region }}"

  tasks:
    - name: Check if Splunk is installed
      stat:
        path: /opt/splunk/bin/splunk
      register: splunk_executable

    - name: Install required system packages
      apt:
        pkg:
          - python3-pip
          - virtualenv
          - python3-boto3
          - python3-botocore
        state: latest
        update_cache: true

    - name: Retrieve AWS Credentials from HashiCorp Vault
      # NOTE: The secret path is created in the main terraform repo when the user is created and key stored in vault at path below
      set_fact:
        aws_creds: "{{ lookup('hashi_vault', 'secret=kv/data/aws/iam_access_keys/terraform_admin token={{ hashicorp_vault_token }} url={{ hashicorp.vault.address }}') }}"

    - name: Create Splunk Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: 0755
        owner: automation
        group: automation
      with_items:
        - "/opt/splunk/"
        - "/opt/splunk/var/log/"
        - "/opt/splunk/etc/licenses/"
        - "/opt/splunk/etc/system/local/"
        - "/opt/splunk/etc/openldap/"
        - "/opt/splunk/etc/auth/audit"

    - name: Download splunkserver.deb from S3
      aws_s3:
        bucket: "{{ env_context }}-levantine-terraform-bucket"
        object: "splunk/splunk-9.2.1-78803f08aabb-linux-2.6-amd64.deb"
        dest: "~/splunk-9.2.1-78803f08aabb-linux-2.6-amd64.deb"
        mode: get
        aws_access_key: "{{ aws_creds.access_key }}"
        aws_secret_key: "{{ aws_creds.secret_key }}"
        region: "{{ aws.default_region }}"
      when: splunk_executable.stat.exists == False
      register: splunk_download

    - name: Install splunkserver.deb
      ansible.builtin.apt:
        deb: "~/splunk-9.2.1-78803f08aabb-linux-2.6-amd64.deb"
      when: splunk_download.changed
      register: splunk_install

    - name: Enable Splunk systemd boot-start
      ansible.builtin.command:
        cmd: "/opt/splunk/bin/splunk enable boot-start -user automation -systemd-managed 1 --accept-license --answer-yes --no-prompt"
      when: splunk_install.changed

    - name: Delete splunkserver.deb
      ansible.builtin.file:
        path: "~/splunk-9.2.1-78803f08aabb-linux-2.6-amd64.deb"
        state: absent